### ISSUE TITLE
🛑 EDAMmap webapp not accessible 🙁

### ISSUE THREAD

**Issue by matuskalas** [edamontology/edammap#18]
Hey @jaanisoe @hedi-ee

Unfortunately https://biit.cs.ut.ee/edammap/ isn't accessible 😥

Insecure HTTP is forced to HTTPS, and the latter is not set up at the moment:

![image](https://user-images.githubusercontent.com/992660/216690002-976bb1a6-55bf-4606-9d74-dc1ae07bab41.png)

Is it just a certificate issue, or anything worse?

**We're extremely eager to use it! 😊**

(And as it says it stores cookies, is it some tracker, then possibly requiring GDPR, or is it just a plain webapp that could even work via pure HTTP?)

**Comment by jaanisoe** [comment]
Hi

I took it down some time ago on purpose. It should be back up now with some slight updates and fixes.

There aren't any tracking cookies, in fact the EDAMmap server proper does not set any cookies at all. The one session cookie you are seeing is set by some proxy I think.

The API is also now up, if you want to use it: https://edammap.readthedocs.io/en/stable/api.html

**Comment by matuskalas** [comment]
Hooray, fantastic! 🥇🙌🏽🐙👾🦑
Million thanks for all the fixes and the new releases!!! 🙏🏽🙏🏽🙇🏽‍♂️
I'm going to study your amazing EDAMmap in its details now, looking forward!
And sorry for keeping you up until the middle of the night :(
