### ISSUE TITLE
Problem building the project 'Non-resolvable parent POM ...'

### ISSUE THREAD

**Issue by bug1303** [edamontology/edammap#2]
I did manage to build the latest [release version (v0.1.1)](https://github.com/edamontology/edammap/releases/tag/v0.1.1) from source with a simple `mvn package` command. However, when trying to build the latest version from the master branch, I get:

[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for mapper:mapper:1.0-SNAPSHOT: Could not find artifact edammap:edammap:pom:0.0.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 13, column 11
 @ 
[...]

**Comment by bug1303** [comment]
Turns out, there was an easy fix to the problem...

```
$ git diff 
diff --git a/mapper/pom.xml b/mapper/pom.xml
index 321708f..839d6c0 100644
--- a/mapper/pom.xml
+++ b/mapper/pom.xml
@@ -13,7 +13,7 @@
   <parent>
     <groupId>edammap</groupId>
     <artifactId>edammap</artifactId>
-    <version>0.0.1-SNAPSHOT</version>
+    <version>0.2-SNAPSHOT</version>
   </parent>
 
   <properties>
```

**Comment by jaanisoe** [comment]
mapper/ is the initial edamMap code, which I rewrote in edammapper/ some time ago. As no longer needed, removed the whole mapper/ directory (c4caec4e4a398141cca2297cb73ed8a5eb84f94d)
