### ISSUE TITLE
Suppress mapping to "organisational" EDAM concepts

### ISSUE THREAD

**Issue by joncison** [edamontology/edammap#4]
In EDAM, some concepts are primarily for organising the concepts graph, and are *not* intended for annotation (see https://github.com/edamontology/edamontology/issues/265).  For now (this will change) these are recorded in EDAM.owl like this:

``<uiTip>Not recommended for annotation in bio.tools.</uiTip>`` 

@hansioan and I made a subset of such terms (below) which edammapper **should not** generate a mapping for:
http://edamontology.org/topic_0003 | Topic
http://edamontology.org/operation_0004 | Operation
http://edamontology.org/data_0006 | Data
http://edamontology.org/format_1915 | Format
http://edamontology.org/operation_2424 | Comparison
http://edamontology.org/operation_2430 | Design
http://edamontology.org/operation_2928 | Alignment
http://edamontology.org/operation_2945 | Analysis
http://edamontology.org/operation_3429 | Generation
http://edamontology.org/operation_3438 | Calculation
http://edamontology.org/operation_3465 | Correlation
http://edamontology.org/operation_2423 | Prediction and recognition
http://edamontology.org/operation_3434 | Conversion
http://edamontology.org/operation_0226 | Annotation
http://edamontology.org/operation_0227 | Indexing
http://edamontology.org/operation_2990 | Classification

**Comment by joncison** [comment]
Also:
http://edamontology.org/topic_3391 | Omics

**Comment by jaanisoe** [comment]
Implemented. If the set of concepts needs to be changed, then change this file:
https://github.com/edamontology/edammap/blob/master/core/src/main/resources/edam/blacklist.txt

**Comment by joncison** [comment]
Great - thanks!  cc @hansioan @matuskalas @veitveit FTI
