### ISSUE TITLE
Couldn't get the webapp to do a mapping ....

### ISSUE THREAD

**Issue by joncison** [edamontology/edammap#5]
Can someone take me through what to do?  I couldn't get any output from the webapp (https://biit.cs.ut.ee/edammap/)

Someone, pls. ping me

@hansioan - did you get it to work?

**Comment by hansioan** [comment]
@joncison @jaanisoe @Ahto123 
I couldn't get it to work, I filled in all the fields and when I click the Map button and nothing happens except that below some fields I get some text saying `FINAL` or `TOTALLY FINAL`.

**Comment by joncison** [comment]
@jaanisoe @Ahto123 - help ! :)    It looks awesome by the way!

**Comment by ahtosalumets** [comment]
I cannot replicate this problem, it seems to work fine for me. What was your input?

**Comment by joncison** [comment]
I gave it a short description (text) and link to http://www.cbs.dtu.dk/services/SignalP/

**Comment by hansioan** [comment]
I tried just now with the information:

Name: SignalP
Keywords: signal peptide cleavage
Short description: Prediction of the presence and location of signal peptide cleavage sites in amino acid sequences from different organisms.
URL of homepage: http://cbs.dtu.dk/services/SignalP/
URLs of documentations: http://www.cbs.dtu.dk/services/SignalP/instructions.php
Publications: 21959131
Existing EDAM Annotation: http://edamontology.org/topic_3510

and I didn't get any output... Could you paste a screenshot of what you get as output?

**Comment by Ahto123** [comment]
Did you also use tool name?

**Comment by ahtosalumets** [comment]
I get following result: https://biit.cs.ut.ee/edammap/0.2-SNAPSHOT/1f102e60-d0e0-433c-b20b-f068ac7fda23/

**Comment by hansioan** [comment]
Yeah, I get none of that... the right hand side is missing completely... in fact nothing really changes after I click the `Map` button.

**Comment by ahtosalumets** [comment]
It seems that it doesn't work with Chrome, but it should work with Safari and Firefox. Until it is fixed, could you use Firefox instead?

**Comment by joncison** [comment]
@hansioan  - I'd suggest asking our curators to take a look under Firefox, and provide initial feedback via GitHub.  I will do the same.

**Comment by hansioan** [comment]
It works on Firefox, I checked now, I will use Firefox, thanks @Ahto123

**Comment by ahtosalumets** [comment]
Now it should work on Chrome as well.

**Comment by joncison** [comment]
awesome!  I confirm it works.  Thanks for quick action.
