### ISSUE TITLE
Add tool tips to "Parameters"

### ISSUE THREAD

**Issue by joncison** [edamontology/edammap#6]
Super-nice to expose the parameters in https://biit.cs.ut.ee/edammap/, but some tool tips explaining what they are would help a lot.    Even just a couple of sentences per parameter would help ...

**Comment by jaanisoe** [comment]
Implemented the tool tips.

Sometimes, the tool tip text might still not be enough for understanding the parameter's function, but further such help could be put in the Readme (#9) or wiki (#10).
