### ISSUE TITLE
Simple API to get results without having to write into the text fields

### ISSUE THREAD

**Issue by veitveit** [edamontology/edammap#7]
How about implementing an API to provide at least some of the fields such as publication, tool name and other urls in https://biit.cs.ut.ee/edammap/?

**Comment by jaanisoe** [comment]
API is up and running. Documentation at: https://github.com/edamontology/edammap/wiki/API. I wouldn't consider the interface stable yet. Feedback welcome.

**Comment by joncison** [comment]
This is a great start, thanks a million Erik.  cc @hansioan FHI.

**Comment by jaanisoe** [comment]
API documentation is at https://edammap.readthedocs.io/en/latest/api.html
